[project]
name = "stargazing"
version = "0.1.0"
description = "Home Assistant custom integration for stargazing"
readme = "README.md"
requires-python = ">=3.13.2,<3.14"

dependencies = [
    "homeassistant==2026.2.3",
    "astral",
    "skyfield",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-homeassistant-custom-component>=0.13.3.16",
    "pytest-asyncio",
    "aioresponses==0.7.9",
]
