#!/usr/bin/env bash
set -e

# Install uv if not present
#if ! command -v uv &> /dev/null; then
#    curl -LsSf https://astral.sh/uv/install.sh | sh
#    export PATH="$HOME/.local/bin:$PATH"
#fi

pip install -r requirements.txt -r requirements-dev.txt